export const MSG_LIST_PAGE_TRY_RESTORE_COMPONENT = "MSG_LIST_PAGE_TRY_RESTORE_COMPONENT";
export const MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS = "MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS";
export const MSG_LIST_PAGE_FETCH_ITEMS_FAIL = "MSG_LIST_PAGE_FETCH_ITEMS_FAIL";
export const MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS = "MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS";
export const MSG_LIST_PAGE_UPDATE_PULLUP_STATUS = "MSG_LIST_PAGE_UPDATE_PULLUP_STATUS";
export const MSG_LIST_PAGE_BACKUP_ISCROLL_Y = "MSG_LIST_PAGE_BACKUP_ISCROLL_Y";
export const MSG_LIST_PAGE_UPDATE_LOADING_STATUS = "MSG_LIST_PAGE_UPDATE_LOADING_STATUS";