    export const MSG_APP_RESTORE_COMPONENT = 'MSG_APP_RESTORE_COMPONENT'
    export const APPBANNERGET = 'APPBANNERGET'
    export const FETCHBANNER_SUCCESS = 'FETCHBANNER_SUCCESS'
    export const FETCHSALSE_SUCCESS = 'FETCHSALSE_SUCCESS'