   //App
   export const APP_RESTORE_COMPONENT = 'APP_RESTORE_COMPONENT'
   export const APPBANNERGET = 'APPBANNERGET'
   export const FETCHBANNER_SUCCESS = 'FETCHBANNER_SUCCESS'
   export const FETCHSALSE_SUCCESS = 'FETCHSALSE_SUCCESS'
   export const FETCHCATELIST_SUCCESS = 'FETCHCATELIST_SUCCESS'
   export const FETCHCATEGOODS_SUCCESS = 'FETCHCATEGOODS_SUCCESS'
   export const UPDATE_CATEID_STATUS = 'UPDATE_CATEID_STATUS'
   export const UPDATE_PULLUP_STATUS = 'UPDATE_PULLUP_STATUS'
   export const UPDATE_LIEVENT_STATUS = 'UPDATE_LIEVENT_STATUS'


   //Search
   // export const SEARCHPAGE_REDDIT = 'SEARCHPAGE_REDDIT'
   // export const REQUESTPAGE_POSTS = 'REQUESTPAGE_POSTS'
   // export const RECEIVEPAGE_POSTS = 'RECEIVEPAGE_POSTS'
   // export const INVALIDATE_REDDIT = 'INVALIDATE_REDDIT'
   export const MSG_LIST_PAGE_TRY_RESTORE_COMPONENT = 'MSG_LIST_PAGE_TRY_RESTORE_COMPONENT'
   export const MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS = 'MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS'
   export const MSG_LIST_PAGE_FETCH_ITEMS_FAIL = 'MSG_LIST_PAGE_FETCH_ITEMS_FAIL'
   export const MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS = 'MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS'
   export const MSG_LIST_PAGE_UPDATE_PULLUP_STATUS = 'MSG_LIST_PAGE_UPDATE_PULLUP_STATUS'
   export const MSG_LIST_UPDATE_SEARCHNUM = 'MSG_LIST_UPDATE_SEARCHNUM'
   export const MSG_LIST_PAGE_BACKUP_ISCROLL_Y = 'MSG_LIST_PAGE_BACKUP_ISCROLL_Y'
   export const MSG_LIST_PAGE_KEYWORD = 'MSG_LIST_PAGE_KEYWORD'
   export const MSG_LIST_PAGE_VOLUME = 'MSG_LIST_PAGE_VOLUME'
   export const MSG_LIST_PAGE_PRICE = 'MSG_LIST_PAGE_PRICE'
   export const MSG_LIST_PAGE_CATE_ID = 'MSG_LIST_PAGE_CATE_ID'

   export const MSG_LIST_PAGE_UPDATE_LOADING_STATUS = 'MSG_LIST_PAGE_UPDATE_LOADING_STATUS'

   //List
   //

   export const LIST_RESTORE_COMPONENT = 'LIST_RESTORE_COMPONENT'
   export const LIST_NAV_SUCCESS = 'LIST_NAV_ITEMS_SUCCESS'
   export const LIST_NAV_FAIL = 'LIST_NAV_FAIL'
   export const LIST_GOODS_SUCCESS = 'LIST_GOODS_SUCCESS'
   export const LIST_GOODS_FAIL = 'LIST_GOODS_FAIL'
   export const LIST_GOODS_UPDATE_CHANGE_STATUS = 'LIST_GOODS_UPDATE_CHANGE_STATUS'
   export const LIST_UPDATE_LOADING_STATUS = 'LIST_UPDATE_LOADING_STATUS'



   //